import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-1 md:grid-cols-2">
          <aside className="sticky top-0 h-screen">
            <header>
              <h1>Jacob Nevitt</h1>
              <h2>Software Developer</h2>
              <h3>
                Bridging the gap between design and functionality one line of
                code at a time
              </h3>
            </header>

            <nav>
              <ul>
                <li>
                  <Link href="#about">About</Link>
                </li>
                <li>
                  <Link href="#tech-stack">Tech Stack</Link>
                </li>
                <li>
                  <Link href="#experience">Experience</Link>
                </li>
                <li>
                  <Link href="#projects">Projects</Link>
                </li>
              </ul>
            </nav>
          </aside>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
