import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { navLink } from "@/types/nav.types";
import SideNav from "./components/ui/side-nav";
import { ClientWrapper } from "./components/context/ClientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks: navLink[] = [
  { href: "about", title: "About", id: 1 },
  { href: "techStack", title: "Tech Stack", id: 2 },
  { href: "experience", title: "Experience", id: 3 },
  { href: "projects", title: "Projects", id: 4 },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-1 md:grid-cols-2">
          <ClientWrapper>
            <SideNav navLinks={navLinks} />
            <main>{children}</main>
          </ClientWrapper>
        </div>
      </body>
    </html>
  );
}
